image: maven:3.8.5-openjdk-17

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install
    - step:
        name: Package Application
        caches:
          - maven
        script:
          - mvn package
        artifacts:
          - target/*.jar